{{- $chartName := include "file-syncer.name" . -}}
{{- $tracingUrl := include "file-syncer.tracingUrl" . -}}
{{- $metricsUrl := include "file-syncer.metricsUrl" . -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-{{ $chartName }}-configmap
data:
  LOG_LEVEL: {{ .Values.env.logLevel | quote }}
  LOG_PRETTY_PRINT_ENABLED: {{ .Values.env.logPrettyPrintEnabled | quote }}
  {{ if .Values.env.tracing.enabled }}
  TELEMETRY_TRACING_ENABLED: 'true'
  TELEMETRY_TRACING_URL: {{ $tracingUrl }}
  {{ end }}
  {{ if .Values.env.metrics.enabled }}
  TELEMETRY_METRICS_ENABLED: 'true'
  TELEMETRY_METRICS_URL: {{ $metricsUrl }}
  {{ end }}
  {{-  $ca := (include "common.ca.merged" . ) | fromYaml }}
  {{- if $ca.enabled }}
  REQUESTS_CA_BUNDLE: {{ printf "%s/%s" $ca.path $ca.key | quote }}
  NODE_EXTRA_CA_CERTS: {{ printf "%s/%s" $ca.path $ca.ca.key | quote }}
  {{- end }}
  FILE_SYNCER_WAIT_TIME: {{ .Values.env.waitTime | quote }}
  FILE_SYNCER_MAX_RETRIES: {{ .Values.env.maxRetries | quote }}
  FILE_SYNCER_INTERVAL_MS: {{ .Values.env.intervalMs | quote }}
  FILE_SYNCER_TASK_POOL_SIZE: {{ .Values.env.taskPoolSize | quote }}
