{
 "title": "File Syncer",
 "time": { "from": "now-1m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": {
     "query": "label_values(jobs_duration_seconds_count,namespace)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Service State",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "up{service_name='file-syncer'}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Processing Tasks",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 4, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "working_tasks", "legendFormat": "{{pod}}" }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(process_cpu_user_seconds_total{service_name=\"file-syncer\"}[3m])*1000",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}